language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y p7zip-full

before_script: composer install 

script: vendor/bin/phpunit -c tests --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ $(phpenv version-name) = "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
