language: php

php:
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php:
        - nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y p7zip-full

before_script: composer install 

script: vendor/bin/phpunit tests --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ $(phpenv version-name) = "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
